import type { paths } from "./sep25_2024.d.ts"; // auto-generated by openapi-typescript
import createClient from "openapi-fetch";
import type {Config} from "../lsp/config.js";

type URL = string;

export type { paths};
export default function makeClient(config: Config) {
  const client = createClient<paths>({
    baseUrl: config.REMOTE_DECISION_SERVICE_URL as URL
  });
  return client;
}