import type { paths } from "./sep25_2024.d.ts"; // auto-generated by openapi-typescript
import createClient from "openapi-fetch";

type URL = string;

export type { paths};
export default function makeClient(decision_service_url: URL) {
  const client = createClient<paths>({
    baseUrl: decision_service_url
  });
  return client;
}