import type { paths } from "./sep25_2024.d.ts"; // auto-generated by openapi-typescript
import createClient from "openapi-fetch";
import type {LSPConfig} from "../lsp/config.js";

export type { paths};
export default function makeClient(config: LSPConfig) {
  const client = createClient<paths>({
    baseUrl: config.get_remote_decision_service_url()
  });
  return client;
}